/**
 * Authentication methods.
 */
export const useAuth = () => {
  const supabase = useSupabaseClient();

  /**
   * Sign in an anonymous user
   *
   * @param captchaToken token generated by the captcha
   * @param userData additional user data
   */
  const signInAnonymously = async (
    captchaToken?: string,
    userData?: object
  ) => {
    try {
      const { data, error } = await supabase.auth.signInAnonymously({
        options: {
          captchaToken,
          data: userData,
        },
      });

      if (error) {
        throw error;
      }
    } catch (error: any) {
      throw error;
    }
  };

  /**
   * Sign out a user
   */
  const signOut = async () => {
    const { error } = await supabase.auth.signOut();

    if (error) throw error;
  };

  return {
    signInAnonymously,
    signOut,
  };
};
